package uz.pdp.botsale.bot;

public interface BotState {
    String CHOOSE_LANG = "CHOOSE_LANG";
    String SHARE_CONTACT = "SHARE_CONTACT";
    String CHOOSE_GENDER = "CHOOSE_GENDER";
    String CHOOSE_CATEGORY = "CHOOSE_CATEGORY";
    String CHOOSE_CHILDREN_CATEGORY = "CHOOSE_CHILDREN_CATEGORY";
    String CHOOSE_BRAND = "CHOOSE_BRAND";
    String CHOOSE_PRODUCT = "CHOOSE_PRODUCT";
    String CHOOSE_SIZE = "CHOOSE_SIZE";
    String CHOOSE_AMOUNT = "CHOOSE_AMOUNT";
    String CHOOSE_LOCATION_OR_ADDRESS = "CHOOSE_LOCATION_OR_ADDRESS";
    String CHOOSE_PAY_TYPE = "CHOOSE_PAY_TYPE";
    String SHOW_BASKET = "SHOW_BASKET";
    String FINISH_ORDER = "FINISH_ORDER";

}
